# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages

before_install:
  - chmod +777 ./travis-tool.sh


env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=FALSE

r_binary_packages:
  - ggplot2
  - magrittr
  - xml2
  - xslt
  - testthat
  - readxl
  - dplyr
  - knitr
  - tidyr
  - rvest
  - rmarkdown
  - covr

r_packages:
  - kableExtra
  - grDevices

notifications:
  email:
    on_success: change
    on_failure: change


after_success:
  - Rscript -e 'library(covr); codecov()'
