on: workflow_dispatch

name: explore

jobs:
  R_script:
    runs-on: windows-latest
    steps:
    - uses: r-lib/actions/setup-r@v2
      with:
         r-version: 4.5.1
         use-public-rspm: true
    - run: |
        Rscript -e 'print("hello")'
        Rscript -e 'print( Sys.info()["sysname"])'
